log_dir: Checkpoint
mixed_precision: fp16
data_folder: wikipedia_20231101.id.processed
batch_size: 48
save_interval: 5000
log_interval: 10
num_process: 1
num_steps: 1000000
dataset_params:
  tokenizer: transfo-xl-wt103
  token_separator: ' '
  token_mask: M
  word_separator: '@@WORD_SEP@@'
  token_maps: token_maps.pkl
  max_mel_length: 512
  word_mask_prob: 0.15
  phoneme_mask_prob: 0.1
  replace_prob: 0.2
model_params:
  vocab_size: 178
  hidden_size: 768
  num_attention_heads: 12
  intermediate_size: 2048
  max_position_embeddings: 512
  num_hidden_layers: 12
  dropout: 0.1
